/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2019-11-15 08:17:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _02_002dajaxRequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Ajax</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#showDiv{\r\n");
      out.write("\t\twidth:200px;\r\n");
      out.write("\t\theight:100px;\r\n");
      out.write("\t\tborder:solid 1px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction getReqData(){\r\n");
      out.write("\t\t//创建ajax引擎对象\r\n");
      out.write("\t\tvar ajax;\r\n");
      out.write("\t\tif (window.XMLHttpRequest) {\r\n");
      out.write("\t\t\tajax = new XMLHttpRequest();\r\n");
      out.write("\t\t} else if (window.ActiveXObject) {\r\n");
      out.write("\t\t\tajax = new ActiveXObject();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//复写onreadystatechange方法\r\n");
      out.write("\t\tajax.onreadystatechange = function(){\r\n");
      out.write("\t\t\t//判断ajax状态码\r\n");
      out.write("\t\t\tif (ajax.readyState == 4) {\r\n");
      out.write("\t\t\t\t//判断响应码\r\n");
      out.write("\t\t\t\tif (ajax.status == 200) {\r\n");
      out.write("\t\t\t\t\t//获取响应信息\r\n");
      out.write("\t\t\t\t\tvar result = ajax.responseText;\r\n");
      out.write("\t\t\t\t\t//处理响应信息\r\n");
      out.write("\t\t\t\t\talert(result);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//发送请求\r\n");
      out.write("\t\t//get请求\r\n");
      out.write("\t\t//ajax.open(\"get\",\"ajax?name=张三&pwd=123\");\r\n");
      out.write("\t\t//ajax.send(null);\r\n");
      out.write("\t\t//post请求\r\n");
      out.write("\t\tajax.open(\"post\",\"ajax\");\r\n");
      out.write("\t\tajax.setRequestHeader(\"Content-Type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\tajax.send(\"name=张三&pwd=123\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3>Ajax大峡谷</h3>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<input type=\"button\" id=\"btn\" value=\"测试\" onclick=\"getReqData()\" >\r\n");
      out.write("\t<div id=\"showDiv\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
