/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2019-11-16 08:19:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _03_002dajaxHero_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajaxUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction getData2(){\r\n");
      out.write("\t\t//获取输入框的值\r\n");
      out.write("\t\tvar name = document.getElementById(\"name\").value;\r\n");
      out.write("\t\tgetData(\"get\",\"user\",\"name=\"+name,function(a){\r\n");
      out.write("\t\t\t//获取响应信息\r\n");
      out.write("\t\t\tvar result = a.responseText;\r\n");
      out.write("\t\t\t//处理响应信息\r\n");
      out.write("\t\t\t//alert(result);\r\n");
      out.write("\t\t\tvar obj = JSON.parse(result);\r\n");
      out.write("\t\t\tvar ta = document.getElementById(\"ta\");\r\n");
      out.write("\t\t\tta.innerHTML=\"\";\r\n");
      out.write("\t\t\tvar tr = ta.insertRow(0);\r\n");
      out.write("\t\t\tvar cell0 = tr.insertCell(0)\r\n");
      out.write("\t\t\tcell0.innerHTML=\"编号\";\r\n");
      out.write("\t\t\tvar cell1 = tr.insertCell(1);\r\n");
      out.write("\t\t\tcell1.innerHTML=\"名称\";\r\n");
      out.write("\t\t\tvar cell2 = tr.insertCell(2);\r\n");
      out.write("\t\t\tcell2.innerHTML=\"描述\";\r\n");
      out.write("\t\t\tvar tr = ta.insertRow(1);\r\n");
      out.write("\t\t\tvar cell0 = tr.insertCell(0)\r\n");
      out.write("\t\t\tcell0.innerHTML=obj.uid;\r\n");
      out.write("\t\t\tvar cell1 = tr.insertCell(1);\r\n");
      out.write("\t\t\tcell1.innerHTML=obj.uname;\r\n");
      out.write("\t\t\tvar cell2 = tr.insertCell(2);\r\n");
      out.write("\t\t\tcell2.innerHTML=obj.des;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3>英雄信息</h3>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<input type=\"text\" id=\"name\" >\r\n");
      out.write("\t<input type=\"button\" value=\"搜索\" onclick=\"getData2()\" >\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<table id=\"ta\" border=\"solid 1px\">\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
